name: Docker-compose to ECS

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
    - uses: actions/checkout@v3
    - name: Update docker-compose version
      run: |
          sudo curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sudo sh
        
    - name: Create ECS Context
      run: docker context create ecs myecscontext --from-env
    - name: verify context
      run: docker context inspect myecscontext
